### ISSUE TITLE
Create SMS & Email Reminders for when equipment is due

### ISSUE THREAD

**Issue by gwadegraham** [capstone-faypublic/faypublic#24]
Creating SMS & Email reminders for when equipment is about to be due.

**Comment by gwadegraham** [comment]
Currently looking at using this app: [for when equipment is due](url)

**Comment by jan-timpe** [comment]
created sms and email reminders for when equipment is due; additionally added Celery support for task scheduling

**Comment by jan-timpe** [comment]
do we need this for class registrations as well?

**Comment by gwadegraham** [comment]
I believe that Dan was hoping for reminders to be sent to people for their upcoming classes, yes
